### ISSUE TITLE
Production Ready？

### ISSUE THREAD

**Issue by cretjs** [romanzy313/trpc-uwebsockets#5]
benchmark is awesome!
```
autocannon -c 500 -d 20 -p 100 http://localhost:8000/api/trpc/hello
```
4x faster than Fastify-trpc
10x faster than express-trpc

and low resource using

env     | memory | cpu
-------- |-----| -----
general  | 55m | 0%
stress test   | 150m | 100%

I want to use it in production. Any risk?

thank you for your work!

**Comment by romanzy313** [comment]
Thank you for your kind words! 

As far as test coverage is concerned, it passes same tests are fastify connector.

The problem with uWebsocketsjs is that it is rather low level and it is difficult to implement features such as static file serving and file uploads. 

I would recommend using Bun as it is based on uWebsockets and is production ready. Here is a [simple integration](https://github.com/sachinraja/trpc-bun).

Trpc was a relevation moment for end-to-end typesafe APIs. Now there are other really good alternatives such as [Eden Treaty](https://elysiajs.com/plugins/eden/overview.html) and [Hono Stacks](https://hono.dev/concepts/stacks). But unfortunately they haven't solved the typesafe subscriptions yet.

**Comment by cretjs** [comment]
Just need json using tRPC.

**Comment by romanzy313** [comment]
Then you are good to go! I have updated this package on npm. Now the latest version includes subscriptions as well. Minimal example in readme is a good starting point.
