### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by yovanoc** [romanzy313/trpc-uwebsockets#8]
isn't better to put trpc and uwebsockets as peer dependencies and allow ranges of versions?

**Comment by romanzy313** [comment]
Yes indeed. I'm not that super familiar with all these ecosystem specific features, kind of afraid to break things.
But there was a "major" change in uWebsocketsjs quite recently. It allowed to store data on per-socket basis inside the uwebsockets itself. The subscription code now depends on it. 

What are the steps to properly indicate that, with peer dependencies?

**Comment by yovanoc** [comment]
storing data on per-socket basis was always here but not fully typed and documented, there is no breaking changes for that.

for peer dependencies we can't put logical OR operator like this for example:

`"the-dependency": "^0.1.0 || ^1.0.0-next.1"`
